manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: steaminwaffles
      url-base: https://github.com/steaminwaffles
  projects:
    - name: zmk
      remote: steaminwaffles
      revision: main
      import: app/west.yml
  self:
    path: config
