manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: justussoh
      url-base: https://github.com/justussoh
  projects:
    - name: zmk
      remote: justussoh
      revision: main
      import: app/west.yml
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
  self:
    path: config
